<?php

use Illuminate\Database\Seeder;

class StreetsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    //Clean everything before populating
    DB::statement('set foreign_key_checks=0;');
    DB::table('streets')->truncate();

    //Initialize Ba Đình districts's street values
    $baDinhvalues = array(
      array('name' => 'An Xá', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Bà Huyện Thanh Quan', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Bắc Sơn', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Bưởi', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Cao Bá Quát', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Cầu Giấy', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Châu Long', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Chu Văn An', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Chùa Một Cột', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Cửa Bắc', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Đặng Dung', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Đặng Tất', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Đào Tấn', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Điện Biên Phủ', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Độc Lập', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Đốc Ngữ', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Đội Cấn', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Đội Nhân', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Giang Văn Minh', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Giảng Võ', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Hàng Bún', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Hàng Đậu', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Hàng Than', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Hoàng Diệu', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Hoàng Hoa Thám', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Hoàng Văn Thụ', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Hòe Nhai', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Hồng Hà', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Hồng Phúc', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Hùng Vương', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Huỳnh Thúc Kháng', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Khúc Hạo', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Kim Mã', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Kim Mã Thượng', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'La Thành', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Lạc Chính', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Láng Hạ', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Lê Duẩn', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Lê Hồng Phong', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Lê Trực', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Liễu Giai', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Linh Lang', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Lý Nam Đế', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Mạc Đĩnh Chi', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Mai Anh Tuấn', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nam Cao', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nam Tràng', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nghĩa Dũng', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Ngọc Hà', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Ngọc Khánh', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Ngũ Xã', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Biểu', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Cảnh Chân', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Chí Thanh', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Công Hoan', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyên Hồng', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Khắc Hiếu', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Khắc Nhu', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Phạm Tuân', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Thái Học', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Thiếp', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Tri Phương', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Nguyễn Trung Trực', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Trường Tộ', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Nguyễn Văn Ngọc', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Núi Trúc', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Ông Ích Khiêm', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Phạm Hồng Thái', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Phạm Huy Thông', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Phan Đình Phùng', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Phan Huy Ích', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Phan Kế Bính', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Phó Đức Chính', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Phúc Xá', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Quần Ngựa', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Quán Thánh', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Sơn Tây', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Tân Ấp', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Thanh Bảo', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Thành Công', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Thanh Niên', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Tôn Thất Đàm', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Tôn Thất Thiệp', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Trần Huy Liệu', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Trần Phú', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Trần Tế Xương', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Trấn Vũ', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Trúc Bạch', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Vạn Bảo', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Văn Cao', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Vạn Phúc', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Vĩnh Phúc', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Yên Ninh', 'type' => 'Phố', 'district_id' => '1'),
      array('name' => 'Yên Phụ', 'type' => 'Đường', 'district_id' => '1'),
      array('name' => 'Yên Thế', 'type' => 'Phố', 'district_id' => '1'),
    );

    //Initialize Ba Vì districts's street values
    $baViValues = array(
      array('name' => 'Quốc lộ 32', 'type' => 'Đường', 'district_id' => '2'),
      array('name' => 'Tản Lĩnh', 'type' => 'Đường', 'district_id' => '2'),
      array('name' => 'Tỉnh Lộ 411C', 'type' => 'Đường', 'district_id' => '2'),
      array('name' => 'Tỉnh lộ 414', 'type' => 'Đường', 'district_id' => '2'),
      array('name' => 'Tỉnh lộ 84', 'type' => 'Đường', 'district_id' => '2'),
      array('name' => 'Tỉnh Lộ 87A', 'type' => 'Đường', 'district_id' => '2'),
      array('name' => 'Tỉnh lộ 88', 'type' => 'Đường', 'district_id' => '2'),
      array('name' => 'Vĩnh Hằng', 'type' => 'Đường', 'district_id' => '2'),
    );

    //Initialize Bắc Từ Liêm districts's street values
    $bacTuLiemValues = array(
      array('name' => 'An Dương Vương', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Cầu Diễn', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Châu Đài', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Cổ Nhuế', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Đăm', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Đặng Thùy Trâm', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Đỗ Nhuận', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Đông Ngạc', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Đức Diễn', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Đức Thắng', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Hồ Tùng Mậu', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Hoàng Công Chất', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Hoàng Liên', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Hoàng Quốc Việt', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Hoàng Tăng Bí', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Kẻ Vẽ', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Kiều Mai', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Kỳ Vũ', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Lê Văn Hiến', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Liên Mạc', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Ngọa Long', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Nguyễn Hoàng Tôn', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Nhật Tảo', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Nhổn', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Phạm Tuấn Tài', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Phạm Văn Đồng', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Phan Bá Vành', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Phú Diễn', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Phú Kiều', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Phú Minh', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Sùng Khang', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Tân Nhuệ', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Tân Phong', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Tân Xuân', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Tây Tựu', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Thanh Lâm', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Thượng Cát', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Thụy Phương', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Trần Cung', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Trung Tựu', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Văn Tiến Dũng', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Văn Trì', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Viên', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Võ Quý Huân', 'type' => 'Phố', 'district_id' => '3'),
      array('name' => 'Xuân Đỉnh', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Xuân Phương', 'type' => 'Đường', 'district_id' => '3'),
      array('name' => 'Yên Nội', 'type' => 'Đường', 'district_id' => '3'),
    );

    //Initialize Cầu Giấy districts's street values
    $cauGiayValues = array(
      array('name' => 'Bưởi', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Cầu Giấy', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Chùa Hà', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Đặng Thùy Trâm', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Dịch Vọng', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Dịch Vọng Hậu', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Đỗ Quang', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Doãn Kế Thiện', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Dương Đình Nghệ', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Dương Quảng Hàm', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Duy Tân', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Hồ Tùng Mậu', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Hoa Bằng', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Hoàng Đạo Thúy', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Hoàng Minh Giám', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Hoàng Ngân', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Hoàng Quốc Việt', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Hoàng Sâm', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Khuất Duy Tiến', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Lê Đức Thọ', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Lê Văn Lương', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Mạc Thái Tổ', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Mạc Thái Tông', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Mai Dịch', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Nghĩa Tân', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Nguyễn Chánh', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Nguyễn Đình Hoàn', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Nguyễn Khả Trạc', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Nguyễn Khang', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Nguyễn Khánh Toàn', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Nguyễn Ngọc Vũ', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Nguyễn Phong Sắc', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Nguyễn Thị Định', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Nguyễn Thị Thập', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Nguyễn Văn Huyên', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Phạm Hùng', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Phạm Thận Duật', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Phạm Tuấn Tài', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Phạm Văn Bạch', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Phạm Văn Đồng', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Phan Văn Trường', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Phùng Chí Kiên', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Quan Hoa', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Quan Nhân', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Thành Thái', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Thọ Tháp', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Tô Hiệu', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Tôn Thất Thuyết', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Bình', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Cung', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Đăng Ninh', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Trần Duy Hưng', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Trần Kim Xuyến', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Quốc Hoàn', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Quý Kiên', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Thái Tông', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Tử Bình', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trần Vỹ', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trung Hòa', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Trung Kính', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Võ Chí Công', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Vũ Phạm Hàm', 'type' => 'Phố', 'district_id' => '4'),
      array('name' => 'Xuân Thủy', 'type' => 'Đường', 'district_id' => '4'),
      array('name' => 'Yên Hòa', 'type' => 'Phố', 'district_id' => '4'),
    );

    //Initialize Chương Mỹ districts's street values
    $chuongMyValues = array(
      array('name' => '6', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => '21', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => '479', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Bắc Sơn', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Chiến Thắng', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Cu Ba', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Hồ Chí Minh', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Nguyễn Anh Trỗi', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Quốc lộ 21', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Quốc lộ 6', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Quốc Lộ 6A', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Tỉnh lộ 419', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Tỉnh lộ 424', 'type' => 'Đường', 'district_id' => '5'),
      array('name' => 'Tỉnh Lộ 80', 'type' => 'Đường', 'district_id' => '5'),
    );

    //Initialize Đan Phượng districts's street values
    $danPhuongValues = array(
      array('name' => '79', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Gò Mèo', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Hoàng Quốc Việt', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Nguyễn Thái Học', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Phan Đình Phùng', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Phùng Hưng', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Phượng Trì', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Quốc lộ 32', 'type' => 'Đường', 'district_id' => '6'),
      array('name' => 'Thụy Ứng', 'type' => 'Đường', 'district_id' => '6'),
    );

    //Initialize Đông Anh districts's street values
    $dongAnhValues = array(
      array('name' => 'Bắc Hồng', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Cao Lỗ', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Cổ Loa', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Đản Dị', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Đào Cam Mộc', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Đào Duy Tùng', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Đông Hội', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Dục Nội', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Dục Tú', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Ga Đông Anh', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Gia Lương', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Hải Bối', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Lâm Tiên', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Lê Hữu Tựu', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Liên Hà', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Nam Hồng', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Nguyên Khê', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Nguyễn Thực', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Phúc Lộc', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Phương Trạch', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Thư Lâm', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Thụy Lâm', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Thụy Lôi', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Uy Nỗ', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Vân Hà', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Vân Nội', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Vân Trì', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Việt Hùng', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Võ Nguyên Giáp', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Võ Văn Kiệt', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Xuân Canh', 'type' => 'Đường', 'district_id' => '7'),
      array('name' => 'Yên Thường', 'type' => 'Đường', 'district_id' => '7'),
    );

    //Initialize Đống Đa districts's street values
    $dongDaValues = array(
      array('name' => 'An Trạch', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Bích Câu', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Cát Linh', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Cầu Giấy', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Cầu Mới', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Chợ Khâm Thiên', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Chùa Bộc', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Chùa Láng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Đặng Tiến Đông', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Đặng Trần Côn', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Đặng Văn Ngữ', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Đào Duy Anh', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Đoàn Thị Điểm', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Đông Các', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Đông Tác', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Giải Phóng', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Giảng Võ', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Hàng Cháo', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Hào Nam', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Hồ Đắc Di', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Hồ Giám', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Hoàng Cầu', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Hoàng Ngọc Phách', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Hoàng Tích Trí', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Huỳnh Thúc Kháng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Khâm Thiên', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Khương Thượng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Kim Hoa', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'La Thành', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Láng', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Láng Hạ', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Lê Duẩn', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Lương Định Của', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Lý Văn Phức', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Mai Anh Tuấn', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nam Đồng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Ngô Sĩ Liên', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Ngô Tất Tố', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nguyễn Chí Thanh', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Nguyên Hồng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nguyễn Khuyến', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nguyễn Lương Bằng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nguyễn Như Đổ', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nguyễn Phúc Lai', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nguyễn Thái Học', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Nguyễn Trãi', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Ô Chợ Dừa', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Phạm Ngọc Thạch', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Phan Phù Tiên', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Phan Văn Trị', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Pháo Đài Láng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Phương Mai', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Quốc Tử Giám', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Tây Sơn', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Thái Hà', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Thái Thịnh', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Tôn Đức Thắng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Tôn Thất Tùng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Trần Hữu Tước', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Trần Quang Diệu', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Trần Quý Cáp', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Trịnh Hoài Đức', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Trúc Khê', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Trung Liệt', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Trường Chinh', 'type' => 'Đường', 'district_id' => '8'),
      array('name' => 'Văn Miếu', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Vĩnh Hồ', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Võ Văn Dũng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Vọng', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Vũ Ngọc Phan', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Vũ Thạnh', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Xã Đàn', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Y Miếu', 'type' => 'Phố', 'district_id' => '8'),
      array('name' => 'Yên Lãng', 'type' => 'Phố', 'district_id' => '8'),
    );

    //Initialize Gia Lâm districts's street values
    $giaLamValues = array(
      array('name' => 'Cổ Bi', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Đa Tốn', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Đặng Phúc Thông', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Đình Xuyên', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Dương Hà', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Dương Quang', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Dương Xá', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Hà Huy Tập', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Kiêu Kỵ', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Ngô Xuân Quảng', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Nguyễn Bình', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Nguyễn Đức Thuận', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Nguyễn Huy Nhuận', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Ninh Hiệp', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Phan Đăng Lưu', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Phù Đổng', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Phú Thị', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Thiên Đức', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Trâu Quỳ', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Trung Màu', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Ỷ Lan', 'type' => 'Đường', 'district_id' => '9'),
      array('name' => 'Yên Thường', 'type' => 'Đường', 'district_id' => '9'),
    );

    //Initialize Hà Đông districts's street values
    $haDongValues = array(
      array('name' => '19-5', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'An Hòa', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Ao Sen', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Ba La', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Bà Triệu', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Bạch Thái Bưởi', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Bế Văn Đàn', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Biên Giang', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Bùi Bằng Đoàn', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Cao Thắng', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Cầu Am', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Cầu Tuân', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Chiến Thắng', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Chu Văn An', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Đa Sĩ', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Đại An', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Đại Mỗ', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Đinh Tiên Hoàng', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Do Lộ', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Động Lãm', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Hà Trì', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Hoàng Diệu', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Hoàng Hoa Thám', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Hoàng Văn Thụ', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Huỳnh Thúc Kháng', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lê Anh Xuân', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lê Hồng Phong', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lê Lai', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lê Lợi', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lê Quý Đôn', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lê Trọng Tấn', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Lụa', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lương Ngọc Quyến', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lương Văn Can', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lý Thường Kiệt', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Lý Tự Trọng', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Mậu Lương', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Minh Khai', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Mộ Lao', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Ngô Gia Khảm', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Ngô Gia Tự', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Ngô Quyền', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Ngô Thì Nhậm', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Ngô Thì Sĩ', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nguyễn Công Trứ', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nguyễn Khuyến', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Nguyễn Thái Học', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nguyễn Thượng Hiền', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nguyễn Trãi', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nguyễn Trực', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Nguyễn Văn Lộc', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nguyễn Văn Trỗi', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nguyễn Viết Xuân', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Nhuệ Giang', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phan Bội Châu', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phan Chu Trinh', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phan Đình Giót', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phan Đình Phùng', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phan Huy Chú', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phú Lãm', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phú Lương', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Phùng Hưng', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Quang Trung', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Tản Đà', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Tây Sơn', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Thanh Bình', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Thành Công', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Thanh Lãm', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Thượng Mạo', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Tiểu Công Nghệ', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Tô Hiến Thành', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Tô Hiệu', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Tố Hữu', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Trần Đăng Ninh', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Trần Hưng Đạo', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Trần Phú', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Trần Văn Chuông', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Trinh Lương', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Trưng Nhị', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Trưng Trắc', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Trương Công Định', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Văn La', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Văn Phú', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Vạn Phúc', 'type' => 'Đường', 'district_id' => '10'),
      array('name' => 'Văn Quán', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Văn Yên', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Võ Thị Sáu', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Xa La', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Xốm', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Yên Bình', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Yên Lộ', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Yên Phúc', 'type' => 'Phố', 'district_id' => '10'),
      array('name' => 'Yết Kiêu', 'type' => 'Phố', 'district_id' => '10'),
    );

    //Initialize Hai Bà Trưng districts's street values
    $haiBaTrungValues = array(
      array('name' => '8-3', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Bà Triệu', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Bạch Đằng', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Bạch Mai', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Bùi Ngọc Dương', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Bùi Thị Xuân', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Cảm Hội', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Cao Đạt', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Chùa Vua', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Đại Cồ Việt', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Đại La', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Đỗ Hành', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Đỗ Ngọc Du', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Đoàn Trần Nghiệp', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Đội Cung', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Đống Mác', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Đồng Nhân', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Giải Phóng', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Hàn Thuyên', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Hàng Chuối', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Hồ Xuân Hương', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Hoa Lư', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Hòa Mã', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Hoàng Mai', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Hồng Mai', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Huế', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Hương Viên', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Kim Ngưu', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lạc Trung', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lãng Yên', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lê Đại Hành', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lê Duẩn', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lê Gia Đỉnh', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lê Ngọc Hân', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lê Quý Đôn', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lê Thanh Nghị', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lê Văn Hưu', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Liên Trì', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lò Đúc', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Lương Yên', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Mạc Thị Bưởi', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Mai Hắc Đế', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Minh Khai', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Ngô Thì Nhậm', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn An Ninh', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Bỉnh Khiêm', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Cao', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Công Trứ', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Đình Chiểu', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Du', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Hiền', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Huy Tự', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Khoái', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Nguyễn Quyền', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Thượng Hiền', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Nguyễn Trung Ngạn', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Phạm Đình Hổ', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Phù Đổng Thiên Vương', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Phùng Khắc Khoan', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Quang Trung', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Quỳnh Lôi', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Quỳnh Mai', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Tạ Quang Bửu', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Tam Trinh', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Tăng Bạt Hổ', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Tây Kết', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Thái Phiên', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Thanh Nhàn', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Thể Giao', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Thi Sách', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Thiền Quang', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Thịnh Yên', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Thọ Lão', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Tô Hiến Thành', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trần Bình Trọng', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trần Cao Vân', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trần Đại Nghĩa', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trần Hưng Đạo', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trần Khánh Dư', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Trần Khát Chân', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Trần Nhân Tông', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trần Thánh Tông', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trần Xuân Soạn', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Triệu Việt Vương', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Trương Định', 'type' => 'Đường', 'district_id' => '11'),
      array('name' => 'Trương Hán Siêu', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Tuệ Tĩnh', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Tương Mai', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Vân Đồn', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Vân Hồ', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Vạn Kiếp', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Vĩnh Tuy', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Võ Thị Sáu', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Vọng', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Vũ Hữu Lợi', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Yên Bái', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Yên Lạc', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Yersin', 'type' => 'Phố', 'district_id' => '11'),
      array('name' => 'Yết Kiêu', 'type' => 'Phố', 'district_id' => '11'),
    );

    //Initialize Hoài Đức districts's street values
    $hoaiDucValues = array(
      array('name' => '32', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => '70', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => '72', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => '79', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => '422', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Đại lộ Thăng Long', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Đồng Nhân', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Lai Xá', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Láng Hòa Lạc', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Lê Trọng Tấn', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Lê Văn Lương', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Quốc lộ 32', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Thụy Ứng', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Tỉnh Lộ 422B', 'type' => 'Đường', 'district_id' => '12'),
      array('name' => 'Yên Vĩnh', 'type' => 'Đường', 'district_id' => '12'),
    );

    //Initialize Hoàn Kiếm districts's street values
    $hoanKiemValues = array(
      array('name' => '19-12', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Ấu Triệu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Bà Triệu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Bạch Đằng', 'type' => 'Đường', 'district_id' => '13'),
      array('name' => 'Báo Khánh', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Bảo Linh', 'type' => 'Đường', 'district_id' => '13'),
      array('name' => 'Bát Đàn', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Bát Sứ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cao Thắng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cầu Đất', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cầu Đông', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cầu Gỗ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Chả Cá', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Chân Cầm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Chợ Gạo', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Chương Dương Độ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cổ Tân', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cổng Đục', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cửa Đông', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Cửa Nam', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Dã Tượng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đặng Thái Thân', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đào Duy Từ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Điện Biên Phủ', 'type' => 'Đường', 'district_id' => '13'),
      array('name' => 'Đinh Công Tráng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đinh Lễ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đinh Liệt', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đình Ngang', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đinh Tiên Hoàng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đoàn Nhữ Hài', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đông Thái', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đồng Xuân', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Đường Thành', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Gầm Cầu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Gia Ngư', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hạ Hồi', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hà Trung', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hai Bà Trưng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàm Long', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàm Tử Quan', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàn Thuyên', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Bạc', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Bài', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Bè', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Bồ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Bông', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Buồm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Bút', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Cá', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Cân', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Chai', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Chiếu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Chĩnh', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Cót', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Da', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Đào', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Đậu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Điếu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Đồng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Đường', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Gà', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Gai', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Giấy', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Giầy', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Hòm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Khay', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Khoai', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Lược', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Mã', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Mắm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Mành', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Muối', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Ngang', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Nón', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Quạt', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Rươi', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Thiếc', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Thùng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Tre', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Trống', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Vải', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hàng Vôi', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hồ Hoàn Kiếm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hỏa Lò', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Hồng Hà', 'type' => 'Đường', 'district_id' => '13'),
      array('name' => 'Huế', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lãn Ông', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Duẩn', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Lai', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Phụng Hiểu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Thạch', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Thái Tổ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Thánh Tông', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Văn Hưu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lê Văn Linh', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Liên Trì', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lò Rèn', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lò Sũ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lương Ngọc Quyến', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lương Văn Can', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lý Đạo Thành', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lý Nam Đế', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lý Quốc Sư', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lý Thái Tổ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Lý Thường Kiệt', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Mã Mây', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nam Ngư', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Ngõ Gạch', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Ngô Quyền', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Ngô Thì Nhậm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Ngõ Trạm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Ngô Văn Sở', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Chế Nghĩa', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Gia Thiều', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Hữu Huân', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Khắc Cần', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyên Khiết', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Quang Bích', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Siêu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Thái Học', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Thiện Thuật', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Thiếp', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Tư Giản', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Văn Tố', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nguyễn Xí', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nhà Chung', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nhà Hỏa', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Nhà Thờ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Ô Quan Chưởng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phạm Ngũ Lão', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phạm Sư Mạnh', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phan Bội Châu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phan Chu Trinh', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phan Đình Phùng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phan Huy Chú', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phủ Doãn', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phúc Tân', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Phùng Hưng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Quán Sứ', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Quang Trung', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Tạ Hiện', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Thanh Hà', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Thanh Yên', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Thợ Nhuộm', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Thuốc Bắc', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Tô Tịch', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Tông Đản', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Tống Duy Tân', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Trần Bình Trọng', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Trần Hưng Đạo', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Trần Khánh Dư', 'type' => 'Đường', 'district_id' => '13'),
      array('name' => 'Trần Nguyên Hãn', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Trần Nhật Duật', 'type' => 'Đường', 'district_id' => '13'),
      array('name' => 'Trần Phú', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Trần Quang Khải', 'type' => 'Đường', 'district_id' => '13'),
      array('name' => 'Trần Quốc Toản', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Tràng Thi', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Tràng Tiền', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Triệu Quốc Đạt', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Trương Hán Siêu', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Vạn Kiếp', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Vọng Đức', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Vọng Hà', 'type' => 'Phố', 'district_id' => '13'),
      array('name' => 'Yết Kiêu', 'type' => 'Phố', 'district_id' => '13'),
    );

    //Initialize Hoàng Mai districts's street values
    $hoagMaiValues = array(
      array('name' => 'Bằng Liệt', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Bùi Huy Bích', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Bùi Xương Trạch', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Đại Từ', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Đặng Xuân Bảng', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Định Công', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Định Công Hạ', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Định Công Thượng', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Đông Thiên', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Giải Phóng', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Giáp Bát', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Giáp Nhị', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Hoàng Liệt', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Hoàng Mai', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Hồng Quang', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Hưng Phúc', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Khuyến Lương', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Kim Đồng', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Kim Giang', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Linh Đàm', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Linh Đường', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Lĩnh Nam', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Lương Khánh Thiện', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Mai Động', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nam Dư', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nghiêm Xuân Yêm', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Ngọc Hồi', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Ngũ Nhạc', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn An Ninh', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn Cảnh Dị', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn Chính', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn Công Thái', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn Đức Cảnh', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn Duy Trinh', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn Hữu Thọ', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Nguyễn Khoái', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Nguyễn Xiển', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Sở Thượng', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Tam Trinh', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Tân Mai', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Tây Trà', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Thanh Đàm', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Thanh Lân', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Thịnh Liệt', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Thúy Lĩnh', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Trần Điền', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Trần Hòa', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Trần Nguyên Đán', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Trần Thủ Độ', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Trương Định', 'type' => 'Đường', 'district_id' => '14'),
      array('name' => 'Tương Mai', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Vĩnh Hưng', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Vũ Tông Phan', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Yên Duyên', 'type' => 'Phố', 'district_id' => '14'),
      array('name' => 'Yên Sở', 'type' => 'Phố', 'district_id' => '14'),
    );

    //Initialize Long Biên districts's street values
    $longBienValues = array(
      array('name' => 'Ái Mộ', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Bắc Cầu', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Bồ Đề', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Cầu Bây', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Cổ Linh', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Đặng Vũ Hỷ', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Đoàn Khuê', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Đức Giang', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Gia Quất', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Gia Thụy', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Giang Biên', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Hoa Lâm', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Hoàng Như Tiếp', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Huỳnh Tấn Phát', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Huỳnh Văn Nghệ', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Kẻ Tạnh', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Kim Quan', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Lâm Du', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Lâm Hạ', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Lệ Mật', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Long Biên 1', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Long Biên 2', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Lưu Khánh Đàm', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Mai Phúc', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Ngô Gia Khảm', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Ngô Gia Tự', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Ngọc Lâm', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Ngọc Thụy', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Ngọc Trì', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Nguyễn Cao Luyện', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Nguyễn Đức Thuận', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Nguyễn Sơn', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Nguyễn Văn Cừ', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Nguyễn Văn Hưởng', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Nguyễn Văn Linh', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Ô Cách', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Phan Văn Đáng', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Phú Viên', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Phúc Lợi', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Sài Đồng', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Tân Thụy', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Thạch Bàn', 'type' => 'Đường', 'district_id' => '15'),
      array('name' => 'Thạch Cầu', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Thanh Am', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Thép Mới', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Thượng Thanh', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Tình Quang', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Trạm', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Trường Lâm', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Tư Đình', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Vạn Hạnh', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Việt Hưng', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Vũ Xuân Thiều', 'type' => 'Phố', 'district_id' => '15'),
      array('name' => 'Xuân Đỗ', 'type' => 'Phố', 'district_id' => '15'),
    );

    //Initialize Mê Linh districts's street values
    $meLinhValues = array(
      array('name' => '23', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => '353', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => '23B', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Bắc Thăng Long', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Bảo Việt', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Cao tốc Thăng Long Nội Bài', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Cây Xoài', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Dân Sinh', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Hà Phong', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Hoa Bằng Lăng', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Hoa Điệp Vàng', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Hoa Ngọc Lan', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Long Việt', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Phố Yên', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Quang Minh', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Quốc lộ 23', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Quốc lộ 23B', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Quốc lộ 308', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Tỉnh lộ 301', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Tỉnh lộ 312', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Trung Sơn Trầm', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Vành Đai 4', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Võ Văn Kiệt', 'type' => 'Đường', 'district_id' => '16'),
      array('name' => 'Yên Nhân', 'type' => 'Đường', 'district_id' => '16'),
    );

    //Initialize Mỹ Đức districts's street values
    $myDucValues = array(
      array('name' => 'Đại Đồng', 'type' => 'Đường', 'district_id' => '17'),
      array('name' => 'Đại Nghĩa', 'type' => 'Đường', 'district_id' => '17'),
      array('name' => 'Tế Tiêu', 'type' => 'Đường', 'district_id' => '17'),
      array('name' => 'Thọ Sơn', 'type' => 'Đường', 'district_id' => '17'),
      array('name' => 'Văn Giang', 'type' => 'Đường', 'district_id' => '17'),
    );

    //Initialize Nam Từ Liêm districts's street values
    $namTuLiemValues = array(
      array('name' => 'Bùi Xuân Phái', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Cao Xuân Huy', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Cầu Cốc', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Cầu Diễn', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Châu Văn Liêm', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Cương Kiên', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Đại Linh', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Đại lộ Thăng Long', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Đại Mỗ', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Đình Thôn', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Đỗ Đình Thiện', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Đỗ Đức Dục', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Do Nha', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Đỗ Xuân Hợp', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Đồng Me', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Dương Đình Nghệ', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Duy Tân', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Hàm Nghi', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Hồ Tùng Mậu', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Hoài Thanh', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Hòe Thị', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Hữu Hưng', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Lê Đức Thọ', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Lê Quang Đạo', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Lương Thế Vinh', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Lưu Hữu Phước', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Mạc Thái Tổ', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Mạc Thái Tông', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Mễ Trì', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Mễ Trì Hạ', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Mễ Trì Thượng', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Miếu Đầm', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Miêu Nha', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Mỹ Đình', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Ngọc Trục', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Nguyễn Cơ Thạch', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Nguyễn Đổng Chi', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Nguyễn Hoàng', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Nguyễn Trãi', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Nguyễn Xuân Nguyên', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Nhổn', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Phạm Hùng', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Phú Đô', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Phúc Diễn', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Phùng Khoang', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Phương Canh', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Sa Đôi', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Tân Mỹ', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Tây Mỗ', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Thanh Bình', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Thị Cấm', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Thiên Hiền', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Tố Hữu', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Tôn Thất Thuyết', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Trần Bình', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Trần Hữu Dực', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Trần Văn Cẩn', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Trần Văn Lai', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Trung Văn', 'type' => 'Đường', 'district_id' => '18'),
      array('name' => 'Tu Hoàng', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Vũ Hữu', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Vũ Quỳnh', 'type' => 'Phố', 'district_id' => '18'),
      array('name' => 'Xuân Phương', 'type' => 'Đường', 'district_id' => '18'),
    );

    //Initialize Phú Xuyên districts's street values
    $phuXuyenValues = array(
      array('name' => '1', 'type' => 'Đường', 'district_id' => '19'),
      array('name' => '73', 'type' => 'Đường', 'district_id' => '19'),
      array('name' => 'Liên Thông', 'type' => 'Đường', 'district_id' => '19'),
      array('name' => 'Quốc lộ 1A', 'type' => 'Đường', 'district_id' => '19'),
      array('name' => 'Truyền Thống', 'type' => 'Đường', 'district_id' => '19'),
    );

    //Initialize Phúc Thọ districts's street values
    $phuThoValues = array(
      array('name' => 'Quốc lộ 32', 'type' => 'Đường', 'district_id' => '20'),
      array('name' => 'Tỉnh lộ 419', 'type' => 'Đường', 'district_id' => '20'),
    );

    //Initialize Quốc Oai districts's street values
    $quocOaiValues = array(
      array('name' => '21', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => '21A', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => '421B', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Đại lộ Thăng Long', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Đồng Bụt', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Đồng Lư', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Hồ Chí Minh', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Láng Hòa Lạc', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Quốc lộ 21A', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Quốc lộ 32', 'type' => 'Đường', 'district_id' => '21'),
      array('name' => 'Yên Quán', 'type' => 'Đường', 'district_id' => '21'),
    );

    //Initialize Sóc Sơn districts's street values
    $socSonValues = array(
      array('name' => '1', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => '2', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => '3', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => '14', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => '16', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => '18', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => '35', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Đa Phúc', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Đền Gióng', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Đồng Lai', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Đông Quan', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Kim Anh', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Miếu Thờ', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Núi Đôi', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Phù Mã', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Phú Tàng', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Quốc lộ 14', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Quốc lộ 16', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Quốc Lộ 2', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Quốc lộ 3', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Quốc Lộ 35', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Quốc lộ 71', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Quốc Lộ 9', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Tân Phú', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Tân Trại', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Thạch Lỗi', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Thân Nhân Trung', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Tỉnh lộ 131', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Tỉnh lộ 135', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Tỉnh lộ 270', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Tỉnh lộ 296', 'type' => 'Đường', 'district_id' => '22'),
      array('name' => 'Tỉnh Lộ 35', 'type' => 'Đường', 'district_id' => '22'),
    );

    //Initialize Sơn Tây districts's street values
    $sonTayValues = array(
      array('name' => '1', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => '2', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => '3', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => '14', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => '16', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => '18', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => '35', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Đa Phúc', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Đền Gióng', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Đồng Lai', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Đông Quan', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Kim Anh', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Miếu Thờ', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Núi Đôi', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Phù Mã', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Phú Tàng', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Quốc lộ 14', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Quốc lộ 16', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Quốc Lộ 2', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Quốc lộ 3', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Quốc Lộ 35', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Quốc lộ 71', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Quốc Lộ 9', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Tân Phú', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Tân Trại', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Thạch Lỗi', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Thân Nhân Trung', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Tỉnh lộ 131', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Tỉnh lộ 135', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Tỉnh lộ 270', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Tỉnh lộ 296', 'type' => 'Đường', 'district_id' => '23'),
      array('name' => 'Tỉnh Lộ 35', 'type' => 'Đường', 'district_id' => '23'),
    );

    //Initialize Tây Hồ districts's street values
    $tayHoValues = array(
      array('name' => 'An Dương', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'An Dương Vương', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Âu Cơ', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Bưởi', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Đặng Thai Mai', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Hoàng Hoa Thám', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Hồng Hà', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Hùng Vương', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Lạc Long Quân', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Mai Xuân Thưởng', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Nghi Tàm', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Nguyễn Đình Thi', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Nguyễn Hoàng Tôn', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Nhật Chiêu', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Phan Đình Phùng', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Phú Gia', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Phú Thượng', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Phú Xá', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Phúc Hoa', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Quảng An', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Quảng Bá', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Quảng Khánh', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Tam Đa', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Tây Hồ', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Thanh Niên', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Thượng Thụy', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Thụy Khuê', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Tô Ngọc Vân', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Trích Sài', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Trịnh Công Sơn', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Từ Hoa', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Vệ Hồ', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Võ Chí Công', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Võng Thị', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Xuân Diệu', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Xuân La', 'type' => 'Đường', 'district_id' => '24'),
      array('name' => 'Yên Hoa', 'type' => 'Phố', 'district_id' => '24'),
      array('name' => 'Yên Phụ', 'type' => 'Đường', 'district_id' => '24'),
    );

    //Initialize Thạch Thất districts's street values
    $thachThatValues = array(
      array('name' => '21', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => '84', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => '42585', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => 'Cần Thơ', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => 'Đại lộ Thăng Long', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => 'Đồng Vàng', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => 'Quốc lộ 21A', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => 'Tỉnh lộ 419', 'type' => 'Đường', 'district_id' => '25'),
      array('name' => 'Tỉnh lộ 84', 'type' => 'Đường', 'district_id' => '25'),
    );

    //Initialize Thanh Oai districts's street values
    $thanhOaiValues = array(
      array('name' => '21B', 'type' => 'Đường', 'district_id' => '26'),
      array('name' => 'Quốc lộ 21B', 'type' => 'Đường', 'district_id' => '26'),
      array('name' => 'Quốc lộ 71', 'type' => 'Đường', 'district_id' => '26'),
    );

    //Initialize Thanh Trì districts's street values
    $thanhTriValues = array(
      array('name' => '1', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => '21', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => '70', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Cầu Bính', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Cầu Bươu', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Cầu Dậu', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Cầu Tó', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Chiến Thắng', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Cổ Điển A', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Cổ Điển B', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Cương Ngô', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Đê Quai', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Đông Mỹ', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Hữu Hòa', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Hữu Lê', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Huỳnh Cung', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Kim Giang', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Lạc Thị', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Lưu Phái', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Ngọc Hồi', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Ngũ Hiệp', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Ngũ Nhạc', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Nguyễn Khoái', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Nguyễn Khuyến', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Nguyễn Xiển', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Nhị Châu', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Phan Trọng Tuệ', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Pháp Vân', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Quốc Bảo', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Quốc Lộ 1', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Quốc lộ 1A', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Quốc lộ 70', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Quỳnh Đô', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Tả Thanh Oai', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Tân Triều', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Thanh Đàm', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Thanh Lân', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Thanh Liệt', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Trần Thủ Độ', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Tranh Khúc', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Triều Khúc', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Tứ Hiệp', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Tựu Liệt', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Vành Đai 3', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Vĩnh Ninh', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Vĩnh Quỳnh', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Vòng Cầu Niệm', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Yên Ngưu', 'type' => 'Đường', 'district_id' => '27'),
      array('name' => 'Yên Xá', 'type' => 'Đường', 'district_id' => '27'),
    );

    //Initialize Thanh Xuân districts's street values
    $thanhXuanValues = array(
      array('name' => 'Bùi Xương Trạch', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Chính Kinh', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Cù Chính Lan', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Cự Lộc', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Định Công', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Giải Phóng', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Giáp Nhất', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Hạ Đình', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Hoàng Đạo Thành', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Hoàng Đạo Thúy', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Hoàng Minh Giám', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Hoàng Ngân', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Hoàng Văn Thái', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Khuất Duy Tiến', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Khương Đình', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Khương Hạ', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Khương Trung', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Kim Giang', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Lê Trọng Tấn', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Lê Văn Lương', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Lê Văn Thiêm', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Lương Thế Vinh', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Ngụy Như Kon Tum', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Nguyễn Huy Tưởng', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Nguyễn Ngọc Nại', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Nguyễn Quý Đức', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Nguyễn Thị Định', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Nguyễn Thị Thập', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Nguyễn Trãi', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Nguyễn Tuân', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Nguyễn Văn Trỗi', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Nguyễn Viết Xuân', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Nguyễn Xiển', 'type' => 'Đường', 'district_id' => '28'),
      array('name' => 'Nhân Hòa', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Phan Đình Giót', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Phương Liệt', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Quan Nhân', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Thượng Đình', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Tố Hữu', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Tô Vĩnh Diện', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Trần Điền', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Triều Khúc', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Trường Chinh', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Vọng', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Vũ Hữu', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Vũ Tông Phan', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Vũ Trọng Phụng', 'type' => 'Phố', 'district_id' => '28'),
      array('name' => 'Vương Thừa Vũ', 'type' => 'Phố', 'district_id' => '28'),
    );

    //Initialize Thường Tín districts's street values
    $thuongTinValues = array(
      array('name' => 'Ga', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Liên Thôn', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Liễu Ngoại', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Nguyễn Tuấn Trình', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Quán Gánh', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Quốc lộ 1A', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Quốc lộ 1B', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Quốc lộ 71', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Quốc Lộ 71A', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Tía', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Tỉnh lộ 427', 'type' => 'Đường', 'district_id' => '29'),
      array('name' => 'Vôi', 'type' => 'Đường', 'district_id' => '29'),
    );

    //Initialize Ứng Hòa districts's street values
    $ungHoaValues = array(
      array('name' => 'Quốc lộ 71', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Quốc lộ 1A', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Quốc lộ 1B', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Vôi', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Quốc Lộ 71A', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Liễu Ngoại', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Ga', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Tía', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Nguyễn Tuấn Trình', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Liên Thôn', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Tỉnh lộ 427', 'type' => 'Đường', 'district_id' => '30'),
      array('name' => 'Quán Gánh', 'type' => 'Đường', 'district_id' => '30'),
    );

    // Mass insert Ba Đình districts's street values to the Streets table
    DB::table('streets')->insert($baDinhvalues);
    // Mass insert Ba Vì districts's street values to the Streets table
    DB::table('streets')->insert($baViValues);
    // Mass insert Bắc Từ Liêm districts's street values to the Streets table
    DB::table('streets')->insert($bacTuLiemValues);
    // Mass insert Cầu Giấy districts's street values to the Streets table
    DB::table('streets')->insert($cauGiayValues);
    // Mass insert Chương Mỹ districts's street values to the Streets table
    DB::table('streets')->insert($chuongMyValues);
    // Mass insert Đan Phượng districts's street values to the Streets table
    DB::table('streets')->insert($danPhuongValues);
    // Mass insert Đông Anh districts's street values to the Streets table
    DB::table('streets')->insert($dongAnhValues);
    // Mass insert Đống Đa districts's street values to the Streets table
    DB::table('streets')->insert($dongDaValues);
    // Mass insert Gia Lâm districts's street values to the Streets table
    DB::table('streets')->insert($giaLamValues);
    // Mass insert Hà Đông districts's street values to the Streets table
    DB::table('streets')->insert($haDongValues);
    // Mass insert Hai Bà Trưng districts's street values to the Streets table
    DB::table('streets')->insert($haiBaTrungValues);
    // Mass insert Hoài Đức districts's street values to the Streets table
    DB::table('streets')->insert($hoaiDucValues);
    // Mass insert Hoàn Kiếm districts's street values to the Streets table
    DB::table('streets')->insert($hoanKiemValues);
    // Mass insert Hoàng Mai districts's street values to the Streets table
    DB::table('streets')->insert($hoagMaiValues);
    // Mass insert Long Biên districts's street values to the Streets table
    DB::table('streets')->insert($longBienValues);
    // Mass insert Mê Linh districts's street values to the Streets table
    DB::table('streets')->insert($meLinhValues);
    // Mass insert Mỹ Đức districts's street values to the Streets table
    DB::table('streets')->insert($myDucValues);
    // Mass insert Nam Từ Liêm districts's street values to the Streets table
    DB::table('streets')->insert($namTuLiemValues);
    // Mass insert Phú Xuyên districts's street values to the Streets table
    DB::table('streets')->insert($phuXuyenValues);
    // Mass insert Phúc Thọ districts's street values to the Streets table
    DB::table('streets')->insert($phuThoValues);
    // Mass insert Quốc Oai districts's street values to the Streets table
    DB::table('streets')->insert($quocOaiValues);
    // Mass insert Sóc Sơn districts's street values to the Streets table
    DB::table('streets')->insert($socSonValues);
    // Mass insert Sơn Tây districts's street values to the Streets table
    DB::table('streets')->insert($sonTayValues);
    // Mass insert Tây Hồ districts's street values to the Streets table
    DB::table('streets')->insert($tayHoValues);
    // Mass insert Thạch Thất districts's street values to the Streets table
    DB::table('streets')->insert($thachThatValues);
    // Mass insert Thanh Oai districts's street values to the Streets table
    DB::table('streets')->insert($thanhOaiValues);
    // Mass insert Thanh Trì districts's street values to the Streets table
    DB::table('streets')->insert($thanhTriValues);
    // Mass insert Thanh Xuân districts's street values to the Streets table
    DB::table('streets')->insert($thanhXuanValues);
    // Mass insert Thường Tín districts's street values to the Streets table
    DB::table('streets')->insert($thuongTinValues);
    // Mass insert Ứng Hòa districts's street values to the Streets table
    DB::table('streets')->insert($ungHoaValues);


    // Mass update slug field
    $streets = App\Street::get();

    foreach ($streets as $street)
    {
      $street->update(['slug' => App\Street::createSlug($street->name)]);
    }
  }
}
