<?php

use Illuminate\Database\Seeder;

class WardsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    // Clean everything before populating
    DB::statement('set foreign_key_checks=0;');
    DB::table('wards')->truncate();

    // Initialize values
    // We will use sql function to generate slug based on name later.
    $values = array(
      array('name' => 'Cống Vị', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Điện Biên', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Đội Cấn', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Giảng Võ', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Kim Mã', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Liễu Giai', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Ngọc Hà', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Ngọc Khánh', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Nguyễn Trung Trực', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Phúc Xá', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Quán Thánh', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Thành Công', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Trúc Bạch', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Vĩnh Phúc', 'slug' => '', 'type' => 'Phường', 'district_id' => 1),
      array('name' => 'Ba Trại', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Ba Vì', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Cẩm Lĩnh', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Cam Thượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Châu Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Chu Minh', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Cổ Đô', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Đông Quang', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Đồng Thái', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Khánh Thượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Minh Châu', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Minh Quang', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Phong Vân', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Phú Châu', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Phú Cường', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Phú Đông', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Phú Phương', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Phú Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Sơn Đà', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Tản Hồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Tản Lĩnh', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Tây Đằng', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 2),
      array('name' => 'Thái Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Thuần Mỹ', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Thụy An', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Tiên Phong', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Tòng Bạt', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Vân Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Vạn Thắng', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Vật Lại', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Yên Bài', 'slug' => '', 'type' => 'Xã', 'district_id' => 2),
      array('name' => 'Cổ Nhuế 1', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Cổ Nhuế 2', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Đông Ngạc', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Đức Thắng', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Liên Mạc', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Minh Khai', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Phú Diễn', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Phúc Diễn', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Tây Tựu', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Thượng Cát', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Thụy Phương', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Xuân Đỉnh', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Xuân Tảo', 'slug' => '', 'type' => 'Phường', 'district_id' => 3),
      array('name' => 'Dịch Vọng', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Dịch Vọng Hậu', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Mai Dịch', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Nghĩa Đô', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Nghĩa Tân', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Quan Hoa', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Trung Hoà', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Yên Hoà', 'slug' => '', 'type' => 'Phường', 'district_id' => 4),
      array('name' => 'Chúc Sơn', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 5),
      array('name' => 'Đại Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Đồng Lạc', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Đồng Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Đông Phương Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Đông Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Hòa Chính', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Hoàng Diệu', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Hoàng Văn Thụ', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Hồng Phong', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Hợp Đồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Hữu Văn', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Lam Điền', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Mỹ Lương', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Nam Phương Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Ngọc Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Phú Nam An', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Phú Nghĩa', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Phụng Châu', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Quảng Bị', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Tân Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Thanh Bình', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Thượng Vực', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Thụy Hương', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Thủy Xuân Tiên', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Tiên Phương', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Tốt Động', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Trần Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Trung Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Trường Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Văn Võ', 'slug' => '', 'type' => 'Xã', 'district_id' => 5),
      array('name' => 'Xuân Mai', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 5),
      array('name' => 'Đan Phượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Đồng Tháp', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Hạ Mỗ', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Hồng Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Liên Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Liên Hồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Liên Trung', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Phùng', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 6),
      array('name' => 'Phương Đình', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Song Phượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Tân Hội', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Tân Lập', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Thọ An', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Thọ Xuân', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Thượng Mỗ', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Trung Châu', 'slug' => '', 'type' => 'Xã', 'district_id' => 6),
      array('name' => 'Bắc Hồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Cổ Loa', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Dục Tú', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Đại Mạch', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Đông Anh', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 7),
      array('name' => 'Đông Hội', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Hải Bối', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Kim Chung', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Kim Nỗ', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Liên Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Mai Lâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Nam Hồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Nguyên Khê', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Tầm Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Thụy Lâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Tiên Dương', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Uy Nỗ', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Vân Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Vân Nội', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Việt Hùng', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Vĩnh Ngọc', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Võng La', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Xuân Canh', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Xuân Nộn', 'slug' => '', 'type' => 'Xã', 'district_id' => 7),
      array('name' => 'Cát Linh', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Hàng Bột', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Khâm Thiên', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Khương Thượng', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Kim Liên', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Láng Hạ', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Láng Thượng', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Nam Đồng', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Ngã Tư Sở', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Ô Chợ Dừa', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Phương Liên', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Phương Mai', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Quang Trung', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Quốc Tử Giám', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Thịnh Quang', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Thổ Quan', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Trung Liệt', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Trung Phụng', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Trung Tự', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Văn Chương', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Văn Miếu', 'slug' => '', 'type' => 'Phường', 'district_id' => 8),
      array('name' => 'Bát Tràng', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Cổ Bi', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Dương Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Dương Quang', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Dương Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Đa Tốn', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Đặng Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Đình Xuyên', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Đông Dư', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Kiêu Kỵ', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Kim Lan', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Kim Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Lệ Chi', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Ninh Hiệp', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Phù Đổng', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Phú Thị', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Trâu Quỳ', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 9),
      array('name' => 'Trung Mầu', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Văn Đức', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Yên Thường', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Yên Viên', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 9),
      array('name' => 'Yên Viên', 'slug' => '', 'type' => 'Xã', 'district_id' => 9),
      array('name' => 'Biên Giang', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Dương Nội', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Đồng Mai', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Hà Cầu', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Kiến Hưng', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'La Khê', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Mộ Lao', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Nguyễn Trãi', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Phú La', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Phú Lãm', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Phú Lương', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Phúc La', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Quang Trung', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Vạn Phúc', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Văn Quán', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Yên Nghĩa', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Yết Kiêu', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Bạch Đằng', 'slug' => '', 'type' => 'Phường', 'district_id' => 10),
      array('name' => 'Bách Khoa', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Bạch Mai', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Bùi Thị Xuân', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Cầu Dền', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Đống Mác', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Đồng Nhân', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Đồng Tâm', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Lê Đại Hành', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Minh Khai', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Ngô Thì Nhậm', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Nguyễn Du', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Phạm Đình Hổ', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Phố Huế', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Quỳnh Lôi', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Quỳnh Mai', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Thanh Lương', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Thanh Nhàn', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Trương Định', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'Vĩnh Tuy', 'slug' => '', 'type' => 'Phường', 'district_id' => 11),
      array('name' => 'An Khánh', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'An Thượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Cát Quế', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Di Trạch', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Dương Liễu', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Đắc Sở', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Đông La', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Đức Giang', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Đức Thượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Kim Chung', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'La Phù', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Lại Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Minh Khai', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Sơn Đồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Song Phương', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Tiền Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Trạm Trôi', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 12),
      array('name' => 'Vân Canh', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Vân Côn', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Yên Sở', 'slug' => '', 'type' => 'Xã', 'district_id' => 12),
      array('name' => 'Chương Dương Độ', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Cửa Đông', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Cửa Nam', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Đồng Xuân', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Bạc', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Bài', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Bồ', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Bông', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Buồm', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Đào', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Gai', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Mã', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Hàng Trống', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Lý Thái Tổ', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Phan Chu Trinh', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Phúc Tân', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Trần Hưng Đạo', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Tràng Tiền', 'slug' => '', 'type' => 'Phường', 'district_id' => 13),
      array('name' => 'Đại Kim', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Định Công', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Giáp Bát', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Hoàng Liệt', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Hoàng Văn Thụ', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Lĩnh Nam', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Mai Động', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Tân Mai', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Thanh Trì', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Thịnh Liệt', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Trần Phú', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Tương Mai', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Vĩnh Hưng', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Yên Sở', 'slug' => '', 'type' => 'Phường', 'district_id' => 14),
      array('name' => 'Bồ Đề', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Cự Khối', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Đức Giang', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Gia Thuỵ', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Giang Biên', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Long Biên', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Ngọc Lâm', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Ngọc Thuỵ', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Phúc Đồng', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Phúc Lợi', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Sài Đồng', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Thạch Bàn', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Thượng Thanh', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Việt Hưng', 'slug' => '', 'type' => 'Phường', 'district_id' => 15),
      array('name' => 'Chi Đông', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 16),
      array('name' => 'Chu Phan', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Đại Thịnh', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Hoàng Kim', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Kim Hoa', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Liên Mạc', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Mê Linh', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Quang Minh', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 16),
      array('name' => 'Tam Đồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Thạch Đà', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Thanh Lâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Tiền Phong', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Tiến Thắng', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Tiến Thịnh', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Tráng Việt', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Tự Lập', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Văn Khê', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'Vạn Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 16),
      array('name' => 'An Mỹ', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'An Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'An Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Bột Xuyên', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Đại Hưng', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Đại Nghĩa', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 17),
      array('name' => 'Đốc Tín', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Đồng Tâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Hồng Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Hợp Thanh', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Hợp Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Hùng Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Hương Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Lê Thanh', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Mỹ Thành', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Phù Lưu Tế', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Phúc Lâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Phùng Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Thượng Lâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Tuy Lai', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Vạn Kim', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Xuy Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 17),
      array('name' => 'Cầu Diễn', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Đại Mỗ', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Mễ Trì', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Mỹ Đình 1', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Mỹ Đình 2', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Phú Đô', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Phương Canh', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Tây Mỗ', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Trung Văn', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Xuân Phương', 'slug' => '', 'type' => 'Phường', 'district_id' => 18),
      array('name' => 'Bạch Hạ', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Châu Can', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Chuyên Mỹ', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Đại Thắng', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Đại Xuyên', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Hoàng Long', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Hồng Minh', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Hồng Thái', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Khai Thái', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Minh Tân', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Nam Phong', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Nam Triều', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Phú Minh', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 19),
      array('name' => 'Phú Túc', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Phú Xuyên', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 19),
      array('name' => 'Phú Yên', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Phúc Tiến', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Phượng Dực', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Quang Lãng', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Quang Trung', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Sơn Hà', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Tân Dân', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Thụy Phú', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Tri Thủy', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Tri Trung', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Văn Hoàng', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Văn Nhân', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Vân Từ', 'slug' => '', 'type' => 'Phường', 'district_id' => 19),
      array('name' => 'Cẩm Đình', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Hát Môn', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Hiệp Thuận', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Liên Hiệp', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Long Xuyên', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Ngọc Tảo', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Phúc Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Phúc Thọ', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 20),
      array('name' => 'Phụng Thượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Phương Độ', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Sen Chiểu', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Tam Hiệp', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Tam Thuấn', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Thanh Đa', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Thọ Lộc', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Thượng Cốc', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Tích Giang', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Trạch Mỹ Lộc', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Vân Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Vân Nam', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Vân Phúc', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Võng Xuyên', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Xuân Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 20),
      array('name' => 'Cấn Hữu', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Cộng Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Đại Thành', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Đồng Quang', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Đông Xuân', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Đông Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Hòa Thạch', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Liệp Tuyết', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Nghĩa Hương', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Ngọc Liệp', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Ngọc Mỹ', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Phú Cát', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Phú Mãn', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Phượng Cách', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Quốc Oai', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 21),
      array('name' => 'Sài Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Tân Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Tân Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Thạch Thán', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Tuyết Nghĩa', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Yên Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 21),
      array('name' => 'Bắc Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Bắc Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Đông Xuân', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Đức Hoà', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Hiền Ninh', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Hồng Kỳ', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Kim Lũ', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Mai Đình', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Minh Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Minh Trí', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Nam Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Phú Cường', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Phù Linh', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Phù Lỗ', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Phú Minh', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Quang Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Sóc Sơn', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 22),
      array('name' => 'Tân Dân', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Tân Hưng', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Tân Minh', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Thanh Xuân', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Tiên Dược', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Trung Giã', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Việt Long', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Xuân Giang', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Xuân Thu', 'slug' => '', 'type' => 'Xã', 'district_id' => 22),
      array('name' => 'Cổ Đông', 'slug' => '', 'type' => 'Xã', 'district_id' => 23),
      array('name' => 'Đường Lâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 23),
      array('name' => 'Kim Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 23),
      array('name' => 'Lê Lợi', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Ngô Quyền', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Phú Thịnh', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Quang Trung', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Sơn Đông', 'slug' => '', 'type' => 'Xã', 'district_id' => 23),
      array('name' => 'Sơn Lộc', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Thanh Mỹ', 'slug' => '', 'type' => 'Xã', 'district_id' => 23),
      array('name' => 'Trung Hưng', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Trung Sơn Trầm', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Viên Sơn', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Xuân Khanh', 'slug' => '', 'type' => 'Phường', 'district_id' => 23),
      array('name' => 'Xuân Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 23),
      array('name' => 'Bưởi', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Nhật Tân', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Phú Thượng', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Quảng An', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Thuỵ Khuê', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Tứ Liên', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Xuân La', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Yên Phụ', 'slug' => '', 'type' => 'Phường', 'district_id' => 24),
      array('name' => 'Bình Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Bình Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Cẩm Yên', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Cần Kiệm', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Canh Nậu', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Chàng Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Dị Nậu', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Đại Đồng', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Đồng Trúc', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Hạ Bằng', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Hương Ngải', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Hữu Bằng', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Kim Quan', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Lại Thượng', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Liên Quan', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 25),
      array('name' => 'Phú Kim', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Phùng Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Tân Xã', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Thạch Hoà', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Thạch Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Tiến Xuân', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Yên Bình', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Yên Trung', 'slug' => '', 'type' => 'Xã', 'district_id' => 25),
      array('name' => 'Bích Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Bình Minh', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Cao Dương', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Cao Viên', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Cự Khê', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Dân Hòa', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Đỗ Động', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Hồng Dương', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Kim An', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Kim Bài', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 26),
      array('name' => 'Kim Thư', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Liên Châu', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Mỹ Hưng', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Phương Trung', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Tam Hưng', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Tân Ước', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Thanh Cao', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Thanh Mai', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Thanh Thùy', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Thanh Văn', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Xuân Dương', 'slug' => '', 'type' => 'Xã', 'district_id' => 26),
      array('name' => 'Duyên Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Đại Áng', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Đông Mỹ', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Hữu Hoà', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Liên Ninh', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Ngọc Hồi', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Ngũ Hiệp', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Tả Thanh Oai', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Tam Hiệp', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Tân Triều', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Thanh Liệt', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Tứ Hiệp', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Văn Điển', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 27),
      array('name' => 'Vạn Phúc', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Vĩnh Quỳnh', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Yên Mỹ', 'slug' => '', 'type' => 'Xã', 'district_id' => 27),
      array('name' => 'Hạ Đình', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Khương Đình', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Khương Mai', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Khương Trung', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Kim Giang', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Nhân Chính', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Phương Liệt', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Thanh Xuân Bắc', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Thanh Xuân Nam', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Thanh Xuân Trung', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Thượng Đình', 'slug' => '', 'type' => 'Phường', 'district_id' => 28),
      array('name' => 'Chương Dương', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Dũng Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Duyên Thái', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Hà Hồi', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Hiền Giang', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Hòa Bình', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Hồng Vân', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Khánh Hà', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Lê Lợi', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Liên Phương', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Minh Cường', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Nghiêm Xuyên', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Nguyễn Trãi', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Nhị Khê', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Ninh Sở', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Quất Động', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Tân Minh', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Thắng Lợi', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Thống Nhất', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Thư Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Thường Tín', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 29),
      array('name' => 'Tiền Phong', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Tô Hiệu', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Tự Nhiên', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Văn Bình', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Vạn Điểm', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Văn Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Vân Tảo', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Văn Tự', 'slug' => '', 'type' => 'Xã', 'district_id' => 29),
      array('name' => 'Cao Thành', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Đại Cường', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Đại Hùng', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Đội Bình', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Đông Lỗ', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Đồng Tân', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Đồng Tiến', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Hòa Lâm', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Hòa Nam', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Hòa Phú', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Hoa Sơn', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Hòa Xá', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Hồng Quang', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Kim Đường', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Liên Bạt', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Lưu Hoàng', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Minh Đức', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Phù Lưu', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Phương Tú', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Quảng Phú Cầu', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Sơn Công', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Tảo Dương Văn', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Trầm Lộng', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Trung Tú', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Trường Thịnh', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Vân Đình', 'slug' => '', 'type' => 'Thị Trấn', 'district_id' => 30),
      array('name' => 'Vạn Thái', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Viên An', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
      array('name' => 'Viên Nội', 'slug' => '', 'type' => 'Xã', 'district_id' => 30),
    );

    // Mass insert to the wards table
    DB::table('wards')->insert($values);

    // Mass update slug field
    $wards = App\Ward::get();

    foreach ($wards as $ward)
    {
      $ward->update(['slug' => App\Ward::createSlug($ward->name)]);
    }
  }
}
